import { useEffect, useState } from 'react';
import { ArrowUpRight, BriefcaseBusiness, Check, ChevronDown, Code2, Cpu, Download, ExternalLink, GraduationCap, Layers3, Mail, Menu, Moon, MoveRight, Network, Send, Sparkles, Sun, Terminal, UserRound, X } from 'lucide-react';
import { portfolioData as data } from './data';

const Github = Code2;
const Linkedin = Network;
const Facebook = UserRound;

type Theme = 'dark' | 'light';

function IconLink({ label, href, children }: { label: string; href: string; children: React.ReactNode }) {
  return <a className="social-link" href={href} aria-label={label} target={href.startsWith('http') ? '_blank' : undefined} rel="noreferrer">{children}</a>;
}

function Navbar({ theme, onThemeToggle }: { theme: Theme; onThemeToggle: () => void }) {
  const [open, setOpen] = useState(false);
  const links = ['about', 'skills', 'projects', 'experience', 'education', 'contact'];
  return <header className="navbar-wrap"><nav className="navbar" aria-label="Main navigation">
    <a className="brand" href="#home" onClick={() => setOpen(false)}><span className="brand-mark">{data.shortName}</span><span>{data.name}</span></a>
    <div className={`nav-links ${open ? 'nav-links-open' : ''}`}>{links.map((link) => <a key={link} href={`#${link}`} onClick={() => setOpen(false)}>{link[0].toUpperCase() + link.slice(1)}</a>)}</div>
    <div className="nav-actions"><button className="theme-toggle" onClick={onThemeToggle} aria-label={`Switch to ${theme === 'dark' ? 'light' : 'dark'} mode`}>{theme === 'dark' ? <Sun size={17} /> : <Moon size={17} />}</button><button className="menu-toggle" onClick={() => setOpen(!open)} aria-label="Toggle navigation menu">{open ? <X size={22} /> : <Menu size={22} />}</button></div>
  </nav></header>;
}

function ProfilePhoto() {
  const [photo, setPhoto] = useState(() => localStorage.getItem('rayhan-profile-photo') || '');
  const handlePhoto = (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { const result = String(reader.result); setPhoto(result); localStorage.setItem('rayhan-profile-photo', result); }; reader.readAsDataURL(file); };
  return <div className="profile-photo-wrap"><div className="profile-photo"><div className="photo-shine" />{photo ? <img src={photo} alt="Rayhan Parvaz" /> : <div className="photo-placeholder"><UserRound size={54} strokeWidth={1.2} /><span>YOUR PHOTO</span></div>}</div><label className="photo-upload"><Download size={14} /> {photo ? 'Change photo' : 'Upload photo'}<input type="file" accept="image/*" onChange={handlePhoto} /></label></div>;
}

function ThreeDHero() {
  const [pointer, setPointer] = useState({ x: 0, y: 0 });
  return <div className="hero-visual" onMouseMove={(event) => { const rect = event.currentTarget.getBoundingClientRect(); setPointer({ x: (event.clientX - rect.left) / rect.width - .5, y: (event.clientY - rect.top) / rect.height - .5 }); }} onMouseLeave={() => setPointer({ x: 0, y: 0 })}>
    <div className="visual-grid" /><div className="visual-ring ring-one" /><div className="visual-ring ring-two" />
    <div className="orb-scene" style={{ transform: `rotateX(${-pointer.y * 9}deg) rotateY(${pointer.x * 12}deg)` }}><div className="orb"><div className="orb-core" /><i className="orb-line line-a" /><i className="orb-line line-b" /><i className="orb-line line-c" /></div><span className="float-cube cube-a" /><span className="float-cube cube-b" /><span className="float-diamond" /></div>
    <div className="code-chip chip-a"><span>&lt;/&gt;</span> build()</div><div className="code-chip chip-b"><span>01</span> neural_net</div><div className="visual-status"><span className="status-dot" /> system / exploring</div>
    <div className="particle-field">{Array.from({ length: 22 }, (_, index) => <i key={index} style={{ '--i': index } as React.CSSProperties} />)}</div>
  </div>;
}

function Hero() { return <section className="hero section-shell" id="home"><div className="hero-copy reveal"><div className="eyebrow"><span className="pulse-dot" /> Available for Opportunities</div><p className="hero-kicker">Hello, I am</p><h1>{data.name}<span className="accent-dot">.</span></h1><h2>{data.title}</h2><p className="hero-description">{data.heroDescription}</p><div className="hero-actions"><a className="button button-primary" href="#projects">View my projects <ArrowUpRight size={17} /></a><a className="button button-ghost" href="#contact">Let's connect <MoveRight size={17} /></a></div><div className="socials"><span>Find me on</span><IconLink label="GitHub" href={data.socials.github}><Github size={18} /></IconLink><IconLink label="LinkedIn" href={data.socials.linkedin}><Linkedin size={18} /></IconLink><IconLink label="Facebook" href={data.socials.facebook}><Facebook size={18} /></IconLink><IconLink label="Email" href={data.socials.email}><Mail size={18} /></IconLink></div></div><div className="hero-stage reveal reveal-delay"><ThreeDHero /><ProfilePhoto /><div className="identity-card"><span className="card-line" /><strong>{data.name}</strong><span>{data.title}</span><small>{data.department}</small><small>{data.university}</small><small>{data.country} <span aria-hidden="true">🇧🇩</span></small></div></div><a className="scroll-cue" href="#about"><span>Scroll to explore</span><ChevronDown size={16} /></a></section>; }

const sectionIntro = (eyebrow: string, title: string, copy: string) => <div className="section-intro"><span className="section-eyebrow">{eyebrow}</span><h2>{title}</h2><p>{copy}</p></div>;

function About() { const cards = [{ label: 'Education', value: data.degree, icon: GraduationCap }, { label: 'University', value: data.university, icon: BriefcaseBusiness }, { label: 'Focus', value: 'AI • Software • Web Development', icon: Sparkles }, { label: 'Location', value: data.country, icon: Network }]; return <section className="content-section section-shell" id="about">{sectionIntro('01 / About', 'Building with curiosity.', 'A little context about the person behind the projects, questions, and experiments.')}<div className="about-layout"><div className="about-statement"><span className="quote-mark">“</span><p>{data.bio}</p><span className="statement-rule" /></div><div className="info-grid">{cards.map(({ label, value, icon: CardIcon }) => <article className="info-card" key={label}><CardIcon size={19} /><span>{label}</span><strong>{value}</strong></article>)}</div></div></section>; }

function Skills() { const groups = [{ name: 'Programming', icon: Terminal, items: data.skills.programming }, { name: 'AI & Technology', icon: Cpu, items: data.skills.ai }, { name: 'Development', icon: Code2, items: data.skills.development }]; return <section className="content-section section-shell" id="skills">{sectionIntro('02 / Capabilities', 'Tools for turning ideas real.', 'A growing toolkit shaped by hands-on learning, practical builds, and a fascination with intelligent systems.')}<div className="skill-grid">{groups.map(({ name, icon: GroupIcon, items }, index) => <article className="skill-card" key={name}><div className="skill-card-head"><span className="skill-number">0{index + 1}</span><GroupIcon size={20} /><h3>{name}</h3></div><div className="skill-list">{items.map((item) => <span key={item}><i />{item}</span>)}</div></article>)}</div></section>; }

function Projects() { return <section className="content-section section-shell" id="projects">{sectionIntro('03 / Selected work', 'Ideas in progress.', 'Projects that explore how technology can make everyday systems more useful, secure, and human.')}<div className="project-grid">{data.projects.map((project, index) => <article className={`project-card accent-${project.accent}`} key={project.title}><div className="project-preview"><div className="preview-top"><span>project_{String(index + 1).padStart(2, '0')}</span><span><i /> <i /> <i /></span></div><div className="preview-art"><Layers3 size={42} strokeWidth={1} /><span>{index === 0 ? 'TASKS / TODAY' : index === 1 ? 'CLASS / ROUTINE' : index === 2 ? 'SIGNAL / ANALYSIS' : 'SECURE / RECOVER'}</span></div><div className="preview-grid-lines" /></div><div className="project-content"><div className="project-title"><span>0{index + 1}</span><h3>{project.title}</h3></div><p>{project.description}</p><div className="tag-list">{project.tags.map((tag) => <span key={tag}>{tag}</span>)}</div><div className="project-links"><a className="text-link muted-link" href="#contact">GitHub <Github size={14} /></a><a className="text-link" href="#contact">Live demo <ExternalLink size={14} /></a></div></div></article>)}</div></section>; }

function Experience() { return <section className="content-section section-shell" id="experience">{sectionIntro('04 / Experience', 'Experience & activities.', 'Learning beyond the classroom through communication, collaboration, and building things together.')}<div className="timeline"><div className="timeline-marker"><span /><span /><span /></div><article className="timeline-entry"><div className="timeline-meta"><span>Activity / 01</span><span>Current</span></div><div><h3>{data.experience.organization}</h3><h4>{data.experience.position}</h4><ul>{data.experience.responsibilities.map((item) => <li key={item}><Check size={13} />{item}</li>)}</ul></div></article></div></section>; }

function Education() { return <section className="content-section section-shell" id="education">{sectionIntro('05 / Education', 'The foundation.', 'A current chapter of study, expanding from core computing concepts toward intelligent software systems.')}<article className="education-card"><div className="education-icon"><GraduationCap size={28} /></div><div><span className="section-eyebrow">Current student</span><h3>{data.degree}</h3><p>{data.university}</p><small>{data.department} department</small></div><span className="education-code">EDU / 01</span></article></section>; }

function Contact() { const [sent, setSent] = useState(false); const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setSent(true); event.currentTarget.reset(); }; return <section className="contact-section" id="contact"><div className="section-shell contact-layout">{sectionIntro('06 / Contact', 'Let’s build something together.', 'Have an idea, project, or opportunity? I’d love to hear from you.')}<div className="contact-grid"><form className="contact-form" onSubmit={handleSubmit}>{['Name', 'Email', 'Subject'].map((label) => <label key={label}>{label}<input required type={label === 'Email' ? 'email' : 'text'} placeholder={`Your ${label.toLowerCase()}`} /></label>)}<label>Message<textarea required rows={5} placeholder="Tell me a little about it..." /></label><button className="button button-primary" type="submit">{sent ? 'Message ready to send' : 'Send message'} {sent ? <Check size={17} /> : <Send size={16} />}</button></form><div className="contact-aside"><div className="contact-symbol"><Mail size={30} /></div><p>Open to conversations about software, AI, creative collaborations, and thoughtful digital products.</p><a className="email-link" href={data.socials.email}>rayhan.parvaz@example.com <ArrowUpRight size={17} /></a><div className="contact-socials"><IconLink label="GitHub" href={data.socials.github}><Github size={18} /></IconLink><IconLink label="LinkedIn" href={data.socials.linkedin}><Linkedin size={18} /></IconLink><IconLink label="Facebook" href={data.socials.facebook}><Facebook size={18} /></IconLink></div></div></div></div></section>; }

function Footer() { return <footer className="footer section-shell"><span>© 2026 {data.name}. All rights reserved.</span><span>made by {data.name}</span></footer>; }

export default function App() { const [theme, setTheme] = useState<Theme>(() => (localStorage.getItem('rayhan-theme') as Theme) || 'dark'); useEffect(() => { document.documentElement.dataset.theme = theme; localStorage.setItem('rayhan-theme', theme); }, [theme]); useEffect(() => { const observer = new IntersectionObserver((entries) => entries.forEach((entry) => { if (entry.isIntersecting) entry.target.classList.add('is-visible'); }), { threshold: .12 }); document.querySelectorAll('.reveal, .content-section, .timeline-entry, .education-card').forEach((element) => observer.observe(element)); return () => observer.disconnect(); }, []); return <div className="site-shell"><div className="ambient ambient-one" /><div className="ambient ambient-two" /><Navbar theme={theme} onThemeToggle={() => setTheme(theme === 'dark' ? 'light' : 'dark')} /><main><Hero /><About /><Skills /><Projects /><Experience /><Education /><Contact /></main><Footer /></div>; }
